name: Docsify

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write # required for OIDC in deploy-pages action

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy theme files
        run: |
          cp -r themes/* docs

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
